export const root = '/'
export const login = '/login'

export const frontend = '/frontend'
export const frontendLibraries = '/frontend/libraries'
export const ios = '/ios'
export const iosLibraries = '/ios/libraries'
export const android = '/android'
export const androidLibraries = '/android/libraries'
export const backend = '/backend'
export const backendLibraries = '/backend/libraries'
