#import "../../components/NodeLibraryDependentsTable/fragment.gql"

query NODE_LIBRARY_QUERY($name: String!, $department: BidaDepartment!) {
  library: npmPackage(name: $name) {
    id
    name
    version

    dependents(first: 100, department: $department) {
      edges {
        node {
          ... on Dependent {
            id
            outdateStatus
            repository {
              name
            }
          }

          ...NodeLibraryDependentsTable_dependents
        }
      }
    }
  }
}
