#import "../../components/NodeProjectsTable/fragment.gql"

query DASHBOARD_QUERY($department: BidaDepartment!) {
  projects(first: 50, department: $department) {
    total: repositoryCount
    edges {
      cursor
      node {
        ... on Repository {
          id
          name
        }

        ...NodeProjectsTable_projects
      }
    }
  }

  archived: projects(department: $department, archived: true) {
    total: repositoryCount
  }
}
